ParseTree
  └── '$'
       └── '{'
            └── PatternEnd
                 └── '}'
                      ├── PatternStartString: '${'
                      ├── PatternEndString: '}'
                      └── Parse: fn
